// <auto-generated />
using System;
using API_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515223627_MitarbeiterFelder")]
    partial class MitarbeiterFelder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Mitarbeiter", b =>
                {
                    b.Property<int>("MitarbeiterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MitarbeiterID"));

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Arbeitszeitkonto")
                        .HasColumnType("numeric");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personalnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Urlaubstage")
                        .HasColumnType("integer");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MitarbeiterID");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("Shared.RFID_Karte", b =>
                {
                    b.Property<int>("KartenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KartenID"));

                    b.Property<int>("MitarbeiterID")
                        .HasColumnType("integer");

                    b.Property<string>("RFID_UID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KartenID");

                    b.ToTable("RFID_Karte");
                });

            modelBuilder.Entity("Shared.Urlaub", b =>
                {
                    b.Property<int>("UrlaubsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UrlaubsID"));

                    b.Property<DateOnly>("Enddatum")
                        .HasColumnType("date");

                    b.Property<bool>("Genehmigt")
                        .HasColumnType("boolean");

                    b.Property<int>("MitarbeiterID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Startdatum")
                        .HasColumnType("date");

                    b.HasKey("UrlaubsID");

                    b.ToTable("Urlaub");
                });

            modelBuilder.Entity("Shared.Zeitbuchung", b =>
                {
                    b.Property<int>("BuchungsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BuchungsID"));

                    b.Property<string>("Buchungstyp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MitarbeiterID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BuchungsID");

                    b.ToTable("Zeitbuchung");
                });
#pragma warning restore 612, 618
        }
    }
}
