@API_Server_HostAddress = http://localhost:5210

GET {{API_Server_HostAddress}}/api/mitarbeiter
Accept: application/json

###

POST {{API_Server_HostAddress}}/api/mitarbeiter
Content-Type: application/json

{
  "vorname": "Max",
  "nachname": "Mustermann",
  "personalnummer": "MA001",
  "aktiv": true
}

###

GET {{API_Server_HostAddress}}/api/zeitbuchung
Accept: application/json

###

POST {{API_Server_HostAddress}}/api/zeitbuchung
Content-Type: application/json

{
  "zeitstempel": "2026-05-05T08:00:00Z",
  "buchungstyp": "Kommen",
  "mitarbeiterID": 1
}

###

GET {{API_Server_HostAddress}}/api/rfidkarte
Accept: application/json

###

POST {{API_Server_HostAddress}}/api/rfidKarte
Content-Type: application/json

{
  "RFID_UID": "A1B2C3D4",
  "mitarbeiterID": 1
}